[package]
name = "notify-rust"
version = "3.0.3"
authors = ["Hendrik Sollich <hendrik@hoodie.de>", "panicbit <panicbit@users.noreply.github.com>"]
description = "Show desktop notifications. Similar to libnotify, but pure rust with no gtk or Qt dependencies."
homepage = "https://github.com/hoodie/notify-rust"
repository = "https://github.com/hoodie/notify-rust"
documentation = "https://hoodie.github.io/notify-rust/"

license = "MIT/Apache-2.0"
keywords = ["desktop", "notification", "notify", "dbus", "libnotify"]
readme = "README.md"

# during mac integration on linux
build = "build.rs"

[dependencies]
dbus = "~0.2"
clippy = {version = "~0.0.23", optional = true}

[features]
default = []
dev = ["clippy"]
